# Generated by Django 4.2.6 on 2023-10-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='site_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
